/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import javax.swing.JFrame;
import InheritanceORM.*;
/**
 *
 * @author wit_w
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JTabbedPane();
        addFulltime = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        createFulltimeEmployee = new javax.swing.JButton();
        fulltimeName = new javax.swing.JTextField();
        fulltimeSalary = new javax.swing.JTextField();
        addParttime = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createParttimeEmployee = new javax.swing.JButton();
        parttimeName = new javax.swing.JTextField();
        parttimeHourswork = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Name");

        jLabel6.setText("Salary");

        createFulltimeEmployee.setText("Create");
        createFulltimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFulltimeEmployeeActionPerformed(evt);
            }
        });

        fulltimeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fulltimeSalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout addFulltimeLayout = new javax.swing.GroupLayout(addFulltime);
        addFulltime.setLayout(addFulltimeLayout);
        addFulltimeLayout.setHorizontalGroup(
            addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFulltimeLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(createFulltimeEmployee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addFulltimeLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fulltimeName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fulltimeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        addFulltimeLayout.setVerticalGroup(
            addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFulltimeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fulltimeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fulltimeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(createFulltimeEmployee)
                .addContainerGap())
        );

        add.addTab("Full Time", addFulltime);

        jLabel4.setText("Name");

        jLabel7.setText("Hours work");

        createParttimeEmployee.setText("Create");
        createParttimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createParttimeEmployeeActionPerformed(evt);
            }
        });

        parttimeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        parttimeHourswork.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout addParttimeLayout = new javax.swing.GroupLayout(addParttime);
        addParttime.setLayout(addParttimeLayout);
        addParttimeLayout.setHorizontalGroup(
            addParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addParttimeLayout.createSequentialGroup()
                .addGroup(addParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addParttimeLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel4)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel7))
                    .addGroup(addParttimeLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(createParttimeEmployee))
                    .addGroup(addParttimeLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(parttimeName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(parttimeHourswork, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        addParttimeLayout.setVerticalGroup(
            addParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addParttimeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(addParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parttimeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parttimeHourswork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(createParttimeEmployee)
                .addContainerGap())
        );

        add.addTab("Part Time", addParttime);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Add Employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createParttimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createParttimeEmployeeActionPerformed
        ParttimeEmployee emp = new ParttimeEmployee(); 
        //emp.setId(Long.parseUnsignedLong(parttimeID.getText()));
        emp.setName(parttimeName.getText());
        emp.setHoursWork(Integer.parseInt(parttimeHourswork.getText()));
        
        DatabaseControl.add(emp);
        //parttimeID.setText("");
        parttimeName.setText("");
        parttimeHourswork.setText("");
    

    }//GEN-LAST:event_createParttimeEmployeeActionPerformed

    private void createFulltimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFulltimeEmployeeActionPerformed
        
        FulltimeEmployee emp = new FulltimeEmployee(); 
        //emp.setId(Long.parseUnsignedLong(fulltimeID.getText()));
        emp.setName(fulltimeName.getText());
        emp.setSalary(Double.parseDouble(fulltimeSalary.getText()));
        
        DatabaseControl.add(emp);
        //fulltimeID.setText("");
        fulltimeName.setText("");
        fulltimeSalary.setText("");
    }//GEN-LAST:event_createFulltimeEmployeeActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane add;
    private javax.swing.JPanel addFulltime;
    private javax.swing.JPanel addParttime;
    private javax.swing.JButton createFulltimeEmployee;
    private javax.swing.JButton createParttimeEmployee;
    private javax.swing.JTextField fulltimeName;
    private javax.swing.JTextField fulltimeSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField parttimeHourswork;
    private javax.swing.JTextField parttimeName;
    // End of variables declaration//GEN-END:variables
}
