/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import InheritanceORM.FulltimeEmployee;
import InheritanceORM.ParttimeEmployee;
import javax.swing.JFrame;

/**
 *
 * @author wit_w
 */
public class Remove extends javax.swing.JFrame {

    /**
     * Creates new form Remove
     */
    public Remove() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JTabbedPane();
        addFulltime = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        removeFulltimeEmployee = new javax.swing.JButton();
        fulltimeID = new javax.swing.JTextField();
        addParttime = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        removeParttimeEmployee = new javax.swing.JButton();
        parttimeID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Remove Employee");

        jLabel3.setText("ID");

        removeFulltimeEmployee.setText("Remove");
        removeFulltimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFulltimeEmployeeActionPerformed(evt);
            }
        });

        fulltimeID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout addFulltimeLayout = new javax.swing.GroupLayout(addFulltime);
        addFulltime.setLayout(addFulltimeLayout);
        addFulltimeLayout.setHorizontalGroup(
            addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFulltimeLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(removeFulltimeEmployee)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(addFulltimeLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fulltimeID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addFulltimeLayout.setVerticalGroup(
            addFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFulltimeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fulltimeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(removeFulltimeEmployee)
                .addContainerGap())
        );

        add.addTab("Full Time", addFulltime);

        jLabel4.setText("ID");

        removeParttimeEmployee.setText("Remove");
        removeParttimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeParttimeEmployeeActionPerformed(evt);
            }
        });

        parttimeID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout addParttimeLayout = new javax.swing.GroupLayout(addParttime);
        addParttime.setLayout(addParttimeLayout);
        addParttimeLayout.setHorizontalGroup(
            addParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addParttimeLayout.createSequentialGroup()
                .addGroup(addParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addParttimeLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel4))
                    .addGroup(addParttimeLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(removeParttimeEmployee))
                    .addGroup(addParttimeLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(parttimeID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        addParttimeLayout.setVerticalGroup(
            addParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addParttimeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(parttimeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(removeParttimeEmployee)
                .addContainerGap())
        );

        add.addTab("Part Time", addParttime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeFulltimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFulltimeEmployeeActionPerformed

        FulltimeEmployee emp = DatabaseControl.findFulltimeEmployeeById(Long.parseLong(fulltimeID.getText()));
 

        DatabaseControl.removeFulltimeEmployee(emp);
        //fulltimeID.setText("");
        fulltimeID.setText("");

    }//GEN-LAST:event_removeFulltimeEmployeeActionPerformed

    private void removeParttimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeParttimeEmployeeActionPerformed
        ParttimeEmployee emp = DatabaseControl.findParttimeEmployeeById(Long.parseLong(parttimeID.getText()));
   

        DatabaseControl.removeParttimeEmployee(emp);
        //parttimeID.setText("");
        parttimeID.setText("");

    }//GEN-LAST:event_removeParttimeEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Remove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane add;
    private javax.swing.JPanel addFulltime;
    private javax.swing.JPanel addParttime;
    private javax.swing.JTextField fulltimeID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField parttimeID;
    private javax.swing.JButton removeFulltimeEmployee;
    private javax.swing.JButton removeParttimeEmployee;
    // End of variables declaration//GEN-END:variables
}
