/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import InheritanceORM.*;
import javax.swing.JFrame;
/**
 *
 * @author wit_w
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        update = new javax.swing.JTabbedPane();
        updateFulltime = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updateFulltimeEmployee = new javax.swing.JButton();
        fulltimeID = new javax.swing.JTextField();
        fulltimeName = new javax.swing.JTextField();
        fulltimeSalary = new javax.swing.JTextField();
        updateParttime = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updateParttimeEmployee = new javax.swing.JButton();
        parttimeID = new javax.swing.JTextField();
        parttimeName = new javax.swing.JTextField();
        parttimeHourswork = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Update Employee");

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        jLabel6.setText("Salary");

        updateFulltimeEmployee.setText("Update");
        updateFulltimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFulltimeEmployeeActionPerformed(evt);
            }
        });

        fulltimeID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fulltimeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fulltimeSalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout updateFulltimeLayout = new javax.swing.GroupLayout(updateFulltime);
        updateFulltime.setLayout(updateFulltimeLayout);
        updateFulltimeLayout.setHorizontalGroup(
            updateFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFulltimeLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(updateFulltimeEmployee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(updateFulltimeLayout.createSequentialGroup()
                .addGroup(updateFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(fulltimeID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(updateFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fulltimeName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(updateFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fulltimeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        updateFulltimeLayout.setVerticalGroup(
            updateFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFulltimeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(updateFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(updateFulltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fulltimeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fulltimeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fulltimeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(updateFulltimeEmployee)
                .addContainerGap())
        );

        update.addTab("Full Time", updateFulltime);

        jLabel4.setText("Name");

        jLabel5.setText("ID");

        jLabel7.setText("Hours work");

        updateParttimeEmployee.setText("Update");
        updateParttimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateParttimeEmployeeActionPerformed(evt);
            }
        });

        parttimeID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        parttimeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        parttimeHourswork.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout updateParttimeLayout = new javax.swing.GroupLayout(updateParttime);
        updateParttime.setLayout(updateParttimeLayout);
        updateParttimeLayout.setHorizontalGroup(
            updateParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateParttimeLayout.createSequentialGroup()
                .addGroup(updateParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateParttimeLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel7))
                    .addGroup(updateParttimeLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(updateParttimeEmployee))
                    .addGroup(updateParttimeLayout.createSequentialGroup()
                        .addComponent(parttimeID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(parttimeName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(parttimeHourswork, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        updateParttimeLayout.setVerticalGroup(
            updateParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateParttimeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(updateParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(updateParttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parttimeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parttimeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parttimeHourswork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(updateParttimeEmployee)
                .addContainerGap())
        );

        update.addTab("Part Time", updateParttime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateFulltimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFulltimeEmployeeActionPerformed

        FulltimeEmployee emp = DatabaseControl.findFulltimeEmployeeById(Long.parseLong(fulltimeID.getText()));
        
        if (!fulltimeName.getText().equals(""))
            emp.setName(fulltimeName.getText());
        if (!fulltimeSalary.getText().equals(""))
            emp.setSalary(Double.parseDouble(fulltimeSalary.getText()));

        DatabaseControl.update(emp);
        //
        fulltimeID.setText("");
        fulltimeName.setText("");
        fulltimeSalary.setText("");
    }//GEN-LAST:event_updateFulltimeEmployeeActionPerformed

    private void updateParttimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateParttimeEmployeeActionPerformed
        ParttimeEmployee emp = DatabaseControl.findParttimeEmployeeById(Long.parseLong(parttimeID.getText()));
        
        if (!parttimeName.getText().equals(""))
            emp.setName(parttimeName.getText());
        if (!parttimeHourswork.getText().equals(""))
            emp.setHoursWork(Integer.parseInt(parttimeHourswork.getText()));

        DatabaseControl.update(emp);
        //
        parttimeID.setText("");
        parttimeName.setText("");
        parttimeHourswork.setText("");

    }//GEN-LAST:event_updateParttimeEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fulltimeID;
    private javax.swing.JTextField fulltimeName;
    private javax.swing.JTextField fulltimeSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField parttimeHourswork;
    private javax.swing.JTextField parttimeID;
    private javax.swing.JTextField parttimeName;
    private javax.swing.JTabbedPane update;
    private javax.swing.JPanel updateFulltime;
    private javax.swing.JButton updateFulltimeEmployee;
    private javax.swing.JPanel updateParttime;
    private javax.swing.JButton updateParttimeEmployee;
    // End of variables declaration//GEN-END:variables
}
